version: '3.8'
services:
  clusters:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # ports:
    #   - '3001:3001' # pasti ada...
    environment:
      - WORKER=16

      # inject on secret...
      - MONGO_URL=
      - MONGO_NAME=
    networks:
      - my_network
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '3000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - clusters
    networks:
      my_network:
        aliases:
          - localhost
          - clusters
          - nginx
    extra_hosts:
      - 'host.docker.internal:host-gateway'
networks:
  my_network:
    driver: bridge
