version: '3.8'
services:
  nodejs_clusters:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - WORKER=10

      # inject on secret...
      - MONGO_URL=
      - MONGO_NAME=
    networks:
      - my_network
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '3000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nodejs_clusters
    networks:
      my_network:
        aliases:
          - localhost
          - nodejs_clusters
          - nginx
    extra_hosts:
      - 'host.docker.internal:host-gateway'
networks:
  my_network:
    driver: bridge
